### ISSUE TITLE
Items from the overworld dissapear in the nether

### ISSUE THREAD

**Issue by D200ui** [sxngsxm/invmanager#1]
(1.19.4 Spigot)
Title, items from the overworld dissapear in the nether with this plugin. 
Also, when trying to delete this plugin, it makes all the player items go away. (thank god I have backups, still can't access nether tho)

**Comment by sxngsxm** [comment]
The plugin is made to have different inventories in different world, you need to configure the config to keep the items from the overworld to the nether. The second is weird because the inventory should be also store in a seperate file from the server.
