### ISSUE TITLE
Plugin wiped inventories of players joining the server

### ISSUE THREAD

**Issue by ImGaribaldi** [sxngsxm/invmanager#2]
Upon loading the plugin for the first time, any player that joins server has any previous inventory data wiped and their inventories cleared completely with no logs in either the world file or plugin files.

**Comment by sxngsxm** [comment]
It is because the plugin saves/loads the inventories to/from own files, so they don't have any items. None of the previous inventories are deleted, because the server saves player inventories in a seperate file.
